
%% Simple use case


%% More advanced use case:
{
function visibleItems = controlDynamicVisibility(paramarray,paramcell)
    buttonGroupVisibleTrue = defaultCheckVisibility(paramarray(5),paramcell(5),true);
    buttonGroupVisibleFalse = defaultCheckVisibility(paramarray(5),paramcell(5),false);
    if strcmp(paramcell{1},'Color picker')
        visibleItems = {1; 1; 0; 0; buttonGroupVisibleFalse{1}};
    elseif strcmp(paramcell{1},'Text field')
        visibleItems = {1; 0; 1; 0; buttonGroupVisibleFalse{1}};
    elseif strcmp(paramcell{1},'Directory')
        visibleItems = {1; 0; 0; 1; buttonGroupVisibleFalse{1}};
    elseif strcmp(paramcell{1},'Checkbox-Integer group')
        visibleItems = {1; 0; 0; 0; buttonGroupVisibleTrue{1}};
    else
        visibleItems = defaultCheckVisibility(paramarray,paramcell,true);
    end
end
% Some documentation for the fields:
button    buttonGroupVisibleTrue = defaultCheckVisibility(paramarray(5),paramcell(5),true);
GroupDoc = 'The groups below may be freely added or deleted to provide dynamic behaviour for the user. The number of minimum and maximum groups can be set with the groupCount parameter.';
colorDoc = 'Click on the color to open the built-in color picker.';
transcendentalDoc = 'Transcendental numbers are those that cannot be expressed as roots of polynomials with only rational coefficients: most known examples are pi and the Euler number: e. Intriguingly they are the reason why the cardinality of real numbers supersede the cardinality of rational numbers, i.e. there are uncountably many transendental numbers.';
S = {...
struct('name','Choose question type','type','enum','values',{{'Color picker','Text field','Directory','Checkbox-Integer group'}},'dynamicVis',true);...
struct('name','My favourite color','type','colorPicker','default',[.3 .8 .5],'doc',colorDoc);...
struct('name','My favourite sentence','type','str','default','The quick lazy fox jumps over the lazy dog.');...
struct('name','My favourite directory','type','dir','default','C:\Users\Public\Documents');...
struct('name','Favourite number','type','buttonGroup','groupCount',[0 10],'doc',buttonGroupDoc,...
    'groupFields',...
    {{
        struct('name','Transendental?','type','checkbox','doc',transcendentalDoc);...
        struct('name','Number','type','int')...
    }},...    
     'default',...
    {{...
        {1,3.141592},...
        {0,1.4142}...        
    }}...
    );...
};
answers = Settings_GUI(S,'checkVisibility',@controlDynamicVisibility);
 }


%% Playing around
% Some documentation for the fields:
buttonGroupDoc = ... 
'The groups below may be freely added or deleted to provide dynamic behaviour for the user. The number of minimum and maximum groups can be set with the groupCount parameter.';
colorDoc = 'Click on the color to open the built-in color picker. If you select the exact blue a slider will appear. ;)';
transcendentalDoc = 'Transcendental numbers are those that cannot be expressed as roots of polynomials with only rational coefficients: most known examples are pi and the Euler number: e. Intriguingly they are the reason why the cardinality of real numbers supersede the cardinality of rational numbers, i.e. there are uncountably many transcendental numbers.';
S = {...
struct('name','Choose question type','type','enum','values',{{'Color picker','Text field','Directory','Checkbox-Integer group'}},'dynamicVis',true);...
struct('name','My favourite color','type','colorPicker','default',[.3 .8 .5],'doc',colorDoc,'dynamicVis',true);...
struct('name','My favourite sentence','type','str','default','The quick lazy fox jumps over the lazy dog.','dynamicVis',true);...
struct('name','My favourite directory','type','dir','default','/data/Technion_analysis/Amygdala/FISH/Aligment/github_repo(1)');...
struct('name','Favourite number','type','buttonGroup','groupCount',[0 10],'doc',buttonGroupDoc,...
    'groupFields',...
    {{
        struct('name','Transcendental?','type','checkbox','doc',transcendentalDoc);...
        struct('name','Number','type','int')...
    }},...    
     'default',...
    {{...
        {1,3.141592},...
        {0,1.4142}...        
    }}...
    );...
struct('name','Easter EGG','type','colorPicker','default',[1 1 0]);...
struct('name','Secret slider','type','slider','lim',[0 10]);...
};
answers = Settings_GUI(S,'checkVisibility',@controlDynamicVisibility,'checkInterimValues',true);
% }
%% 
function visibleItems = controlDynamicVisibility(paramarray,paramcell)
    buttonGroupVisibleTrue = defaultCheckVisibility(paramarray(5),paramcell(5),true);
    buttonGroupVisibleFalse = defaultCheckVisibility(paramarray(5),paramcell(5),false);
    if strcmp(paramcell{1},'Color picker')
        if all(paramcell{2}==[0 0 1]) 
            visibleItems = {1; 1; 0; 0; buttonGroupVisibleFalse{1}; 0; 1};
        else
            visibleItems = {1; 1; 0; 0; buttonGroupVisibleFalse{1}; 0; 0};
        end
    elseif strcmp(paramcell{1},'Text field')
        if strcmp(paramcell{3},'easterEgg')
            visibleItems = {1; 0; 1; 0; buttonGroupVisibleFalse{1}; 1; 0};
        else
            visibleItems = {1; 0; 1; 0; buttonGroupVisibleFalse{1}; 0; 0};
        end
    elseif strcmp(paramcell{1},'Directory')
        visibleItems = {1; 0; 0; 1; buttonGroupVisibleFalse{1}; 0; 0};
    elseif strcmp(paramcell{1},'Checkbox-Integer group')
        visibleItems = {1; 0; 0; 0; buttonGroupVisibleTrue{1}; 0; 0};
    else
        visibleItems = defaultCheckVisibility(paramarray,paramcell,true);
    end
end
